### PR TITLE
Remove composer vendor files from git

### PR DESCRIPTION
**Pull request by pdufour**
Hey so adding vendor files to git causes some problems / duplication, so I removed them and added to gitignore:
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

### CODE REVIEW

**Comment by birgire** [comment]
Thanks @pdufour for your concerns, I appreciate it.

You're correct, we shouldn't keep the vendor directory included, as the plugin gets rather bloated that way ;-)

My initial concern was to support users that don't have ssh access to install or run composer ;-)

Now I'm wondering if we could find a way between, any suggestions?

I noticed that you removed this part:

        require __DIR__.'/vendor/autoload.php';

but I think we would need this kind of check instead:

    if ( file_exists( __DIR__.'/vendor/autoload.php' ) )
        require __DIR__.'/vendor/autoload.php';

cheers

**Comment by pdufour** [comment]
Hey @birgire what about this method? http://blog.madewithlove.be/post/gitattributes/. It seems to be working, I'm not sure if it messes with the flow for publishing to the WP plugin repository though. Basically it excludes certain files from the download that composer uses.

Also side-node would really appreciate having the package available on Packagist :+1:

**Comment by birgire** [comment]
Thanks @pdufour, I will have a closer look at this during the weekend and hopefully we can work something out ;-)

**Comment by birgire** [comment]
Thanks @pdufour 

I added it on Packagist:

   https://packagist.org/packages/birgir/combined-query

**Comment by pdufour** [comment]
Thanks!

**Pull request merged**
