### PR TITLE
README.md - add custom field order example

### PR DESCRIPTION
**Pull request by vov1**
I spend some time to found this solution.
I hope this will help someone.

### CODE REVIEW

**Comment by vov1** [comment]
Sorry for some typo errors

**Comment by birgire** [comment]
Hi @vov1 

thanks for taking the time to construct a PR.

Can you share what problem you where tackling and if you think the examples are too unclear or needs some adjustment? 

Thanks

**Comment by vov1** [comment]
Hi, @birgire 
There is no examples how to order query using custom field.
Code in example 3 don`t work with custom fields.

In this pull request I add an example that shows how to order by custom field by it contains some typo errors. If it`s ok, I will pull new request with fixed typo errors.

**Comment by birgire** [comment]
I can hopefully review it during the weekend and refresh my memory on example 3 ;-)

ps: I noticed wp_postmeta.meta_value in your code.

In general if a table prefix is used, it's better not to assume it's wp_, 

Insead one should use $wpdb->postmeta for the table name.

**Comment by vov1** [comment]
You absolutely right. Thank you.

**Pull request closed without merging**
